APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
DEFAULT_BRANCH: main
DISABLE_LINTERS:
  - CSHARP_DOTNET_FORMAT # Superseded by CSharpier
  - GRAPHQL_GRAPHQL_SCHEMA_LINTER # We have .graphql queries, not schemas.
  - MARKDOWN_MARKDOWN_LINK_CHECK # Superseded by Lychee
  - PYTHON_FLAKE8 # Superseded by Ruff
  - PYTHON_ISORT # Superseded by Ruff
  - TYPESCRIPT_STANDARD # We use Prettier instead.
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FILTER_REGEX_EXCLUDE: \.pnp\.(c|loader\.m)js|\.yarn|dist
FORMATTERS_DISABLE_ERRORS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true

CSS_STYLELINT_CONFIG_FILE: LINTER_DEFAULT
JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_ES_CONFIG_FILE: LINTER_DEFAULT
JAVASCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .js
  - .jsx
JSON_PRETTIER_FILE_EXTENSIONS:
  - .graphql
  - .json
  - .md
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: LINTER_DEFAULT
PYTHON_MYPY_CONFIG_FILE: LINTER_DEFAULT
PYTHON_PYLINT_CONFIG_FILE: LINTER_DEFAULT
PYTHON_RUFF_CONFIG_FILE: LINTER_DEFAULT
REPOSITORY_CHECKOV_CONFIG_FILE: LINTER_DEFAULT
REPOSITORY_GITLEAKS_ARGUMENTS: --log-opts="--full-history"
REPOSITORY_SECRETLINT_ARGUMENTS: --secretlintignore .gitignore
SPELL_CSPELL_CONFIG_FILE: LINTER_DEFAULT
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_ES_CONFIG_FILE: LINTER_DEFAULT
TYPESCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .ts
  - .tsx
