APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
DEFAULT_BRANCH: main
DISABLE_LINTERS:
  - CSHARP_DOTNET_FORMAT # Superseded by CSharpier
  # We use the .graphql extension for queries, not schemas, for the sake of syntax
  # highlighting.
  - GRAPHQL_GRAPHQL_SCHEMA_LINTER
  - PYTHON_FLAKE8 # Superseded by Ruff
  - PYTHON_ISORT # Superseded by Ruff
  - TYPESCRIPT_STANDARD # We use Prettier instead.
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FILTER_REGEX_EXCLUDE: \.pnp\.(c|loader\.m)js|\.yarn|dist
FORMATTERS_DISABLE_ERRORS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
CREDENTIALS_SECRETLINT_ARGUMENTS: --secretlintignore .gitignore
JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_ES_CONFIG_FILE: LINTER_DEFAULT
JSON_PRETTIER_FILE_EXTENSIONS:
  - .graphql
  - .json
  - .md
PYTHON_MYPY_CONFIG_FILE: LINTER_DEFAULT
PYTHON_PYLINT_CONFIG_FILE: LINTER_DEFAULT
PYTHON_RUFF_CONFIG_FILE: LINTER_DEFAULT
REPOSITORY_CHECKOV_CONFIG_FILE: LINTER_DEFAULT
SPELL_CSPELL_CONFIG_FILE: LINTER_DEFAULT
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_ES_CONFIG_FILE: LINTER_DEFAULT
