name: Bump Version
on:
  push:
    branches:
      - $default-branch
jobs:
  bump-version:
    name: Bump Version
    uses: ScribeMD/slack-templates/.github/workflows/bump-version.yaml@main
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_ACTIONS_CHANNEL_ID: ${{ secrets.SLACK_ACTIONS_CHANNEL_ID }}
