name: Test
on:
  pull_request:
    branches:
      - $default-branch
  push:
    branches:
      - $default-branch
jobs:
  test:
    name: Run Pre-commit Hooks
    uses: ScribeMD/pre-commit-action/.github/workflows/test.yaml@main
    permissions:
      contents: write
      pull-requests: read
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_ACTIONS_CHANNEL_ID: ${{ secrets.SLACK_ACTIONS_CHANNEL_ID }}
